FROM apache/airflow:2.10.2

USER root

# Установка Java для PySpark
RUN apt-get update && \
    apt-get install -y default-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Устанавливаем переменную окружения JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/default-java

USER airflow

# Копируем все файлы requirements
COPY requirements.txt /tmp/requirements.txt
COPY requirements-base.txt /tmp/requirements-base.txt
COPY requirements-ml.txt /tmp/requirements-ml.txt
COPY requirements-spark.txt /tmp/requirements-spark.txt
COPY requirements-downloader.txt /tmp/requirements-downloader.txt
COPY requirements-nlp.txt /tmp/requirements-nlp.txt
COPY requirements-dev.txt /tmp/requirements-dev.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt
