FROM openjdk:11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y python3-pip && rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache-dir pyspark numpy

COPY scripts/spark_process.py scripts/config.py ./

CMD ["python3", "spark_process.py"]